export { emailLayout, badge, infoRow, ctaButton } from './email-layout';
export { welcomeTemplate } from './welcome.template';
export type { WelcomeTemplateData } from './welcome.template';
export { interestExpressedTemplate } from './interest-expressed.template';
export type { InterestExpressedTemplateData } from './interest-expressed.template';
export { dealFinalizedTemplate } from './deal-finalized.template';
export type { DealFinalizedTemplateData } from './deal-finalized.template';
export { eventVerifiedTemplate } from './event-verified.template';
export type { EventVerifiedTemplateData } from './event-verified.template';
export { eventRejectedTemplate } from './event-rejected.template';
export type { EventRejectedTemplateData } from './event-rejected.template';
export { companyVerifiedTemplate } from './company-verified.template';
export type { CompanyVerifiedTemplateData } from './company-verified.template';
export { companyRejectedTemplate } from './company-rejected.template';
export type { CompanyRejectedTemplateData } from './company-rejected.template';
export { proposalSubmittedTemplate } from './proposal-submitted.template';
export type { ProposalSubmittedTemplateData } from './proposal-submitted.template';
export { proposalApprovedTemplate } from './proposal-approved.template';
export type { ProposalApprovedTemplateData } from './proposal-approved.template';
export { proposalRejectedTemplate } from './proposal-rejected.template';
export { deliverablesFormSentTemplate } from './deliverables-form-sent.template';
export type { DeliverablesFormSentTemplateData } from './deliverables-form-sent.template';
export type { ProposalRejectedTemplateData } from './proposal-rejected.template';
