export { emailLayout, badge, infoRow, ctaButton } from './email-layout';
export { welcomeTemplate } from './welcome.template';
export type { WelcomeTemplateData } from './welcome.template';
export { verifyEmailTemplate } from './verify-email.template';
export type { VerifyEmailTemplateData } from './verify-email.template';
export { resetPasswordTemplate } from './reset-password.template';
export type { ResetPasswordTemplateData } from './reset-password.template';
export { interestExpressedTemplate } from './interest-expressed.template';
export type { InterestExpressedTemplateData } from './interest-expressed.template';
export { dealFinalizedTemplate } from './deal-finalized.template';
export type { DealFinalizedTemplateData } from './deal-finalized.template';
export { eventVerifiedTemplate } from './event-verified.template';
export type { EventVerifiedTemplateData } from './event-verified.template';
export { eventRejectedTemplate } from './event-rejected.template';
export type { EventRejectedTemplateData } from './event-rejected.template';
export { companyVerifiedTemplate } from './company-verified.template';
export type { CompanyVerifiedTemplateData } from './company-verified.template';
export { companyRejectedTemplate } from './company-rejected.template';
export type { CompanyRejectedTemplateData } from './company-rejected.template';
export { proposalSubmittedTemplate } from './proposal-submitted.template';
export type { ProposalSubmittedTemplateData } from './proposal-submitted.template';
export { proposalForwardedTemplate } from './proposal-forwarded.template';
export type { ProposalForwardedTemplateData } from './proposal-forwarded.template';
export { proposalApprovedTemplate } from './proposal-approved.template';
export type { ProposalApprovedTemplateData } from './proposal-approved.template';
export { proposalRejectedTemplate } from './proposal-rejected.template';
export { proposalChangesRequestedTemplate } from './proposal-changes-requested.template';
export type { ProposalChangesRequestedTemplateData } from './proposal-changes-requested.template';
export { deliverablesFormSentTemplate } from './deliverables-form-sent.template';
export type { DeliverablesFormSentTemplateData } from './deliverables-form-sent.template';
export { deliverablesBatchSentTemplate } from './deliverables-batch-sent.template';
export type { DeliverablesBatchSentTemplateData } from './deliverables-batch-sent.template';
export type { ProposalRejectedTemplateData } from './proposal-rejected.template';
